const schedule={1:{short:'ПН',name:'Понедельник',lessons:[['08:00','08:50','Foreign Language 1 (B1)','Practice','C1.1.225P'],['09:00','09:50','Foreign Language 1 (B1)','Practice','C1.1.225P'],['10:00','10:50','Discrete Mathematics','Lecture','C1.3.264L'],['11:00','11:50','Discrete Mathematics','Lecture','C1.3.264L'],['12:00','12:50','Introduction to Programming','Practice','C1.3.323K'],['13:05','13:55','Introduction to Programming','Practice','C1.3.323K']]},2:{short:'ВТ',name:'Вторник',lessons:[['10:00','10:50','Information and Communication Technologies','Practice','C1.1.357K'],['11:00','11:50','Information and Communication Technologies','Practice','C1.1.357K'],['12:00','12:50','Introduction to Programming','Practice','C1.3.323K'],['16:00','16:50','Introduction to Programming','Lecture','Online'],['17:00','17:50','Introduction to Programming','Lecture','Online']]},3:{short:'СР',name:'Среда',lessons:[['10:00','10:50','Psychology','Lecture','C1.3.370L'],['11:00','11:50','Sociology','Lecture','C1.3.370L'],['12:00','12:50','Discrete Mathematics','Practice','C1.2.226P'],['13:05','13:55','Discrete Mathematics','Practice','C1.2.226P'],['18:00','18:50','Information and Communication Technologies','Lecture','Online'],['19:00','19:50','Information and Communication Technologies','Lecture','Online']]},4:{short:'ЧТ',name:'Четверг',lessons:[]},5:{short:'ПТ',name:'Пятница',lessons:[['08:00','08:50','Discrete Mathematics','Lecture','C1.1.328L'],['10:00','10:50','Sociology','Practice','C1.3.244'],['19:00','19:50','Information and Communication Technologies','Lecture','Online']]},6:{short:'СБ',name:'Суббота',lessons:[['08:00','08:50','Foreign Language 1 (B1)','Practice','C1.1.225P'],['09:00','09:50','Psychology','Practice','C1.3.232P'],['14:00','14:50','Physical Education','Practice','—'],['15:00','15:50','Physical Education','Practice','—'],['18:00','18:50','Foreign Language 1 (B1)','Practice','Online'],['19:00','19:50','Foreign Language 1 (B1)','Practice','Online']]}};
const $=s=>document.querySelector(s),toMinutes=t=>{const[h,m]=t.split(':').map(Number);return h*60+m};
function almatyNow(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Almaty'}))}function today(){const d=almatyNow().getDay();return d===0?1:d}function autoDay(){const n=almatyNow(),d=n.getDay();return d===0?1:n.getHours()>=18?(d===6?1:d+1):d}
let activeDay=autoDay();
function renderTabs(){const d=today();$('#dayTabs').innerHTML=Object.entries(schedule).map(([n,x])=>`<button class="day-tab ${+n===activeDay?'active':''}" type="button" data-day="${n}" aria-pressed="${+n===activeDay}">${x.short}<span>${+n===d?'Сегодня':x.lessons.length+' пар'}</span></button>`).join('');$('#dayTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeDay=+b.dataset.day;render()});}
function render(){const day=schedule[activeDay],now=almatyNow(),min=now.getHours()*60+now.getMinutes(),isToday=activeDay===today();renderTabs();$('#dayName').textContent=day.name;$('#lessonCount').textContent=day.lessons.length?`${day.lessons.length} занятий`:'Свободный день';$('#todayLabel').textContent=isToday?'СЕГОДНЯ':'РАСПИСАНИЕ';$('#heroTitle').textContent=isToday?'Ваш учебный день':day.name;const rows=day.lessons.map(([start,end,name,type,place])=>{const current=isToday&&toMinutes(start)<=min&&min<toMinutes(end),past=isToday&&toMinutes(end)<=min,hasRoom=place!=='Online'&&place!=='—';return `<article class="lesson ${current?'current':''} ${past?'past':''}"><time class="lesson__time" datetime="${start}">${start}<span>до ${end}</span></time><div><div class="lesson__name">${name}</div><div class="lesson__meta"><span class="badge ${type==='Lecture'?'lecture':''}">${type==='Lecture'?'Лекция':'Практика'}</span>${place==='Online'?'<span class="badge online">Онлайн</span>':''}</div></div>${hasRoom?`<button class="room-button" type="button" data-room="${place}" data-subject="${name}"><span aria-hidden="true">→</span>${place}</button>`:`<span class="room-placeholder">${place==='Online'?'Дистанционно':'Спортзал'}</span>`}</article>`}).join('');$('#schedule').innerHTML=rows||'<div class="empty"><span>☀</span><strong>Сегодня занятий нет</strong><br>Можно спокойно планировать день.</div>';$('#schedule').querySelectorAll('.room-button').forEach(b=>b.onclick=()=>openMap(b.dataset.room,b.dataset.subject));updateStatus()}
function updateStatus(){const box=$('#statusCard'),now=almatyNow(),min=now.getHours()*60+now.getMinutes(),lessons=schedule[activeDay].lessons;box.className='status-card';if(activeDay!==today()){box.textContent=lessons.length?`Первая пара в ${lessons[0][0]} · всего ${lessons.length}`:'Занятий нет — свободный день';return}const current=lessons.find(x=>toMinutes(x[0])<=min&&min<toMinutes(x[1])),next=lessons.find(x=>toMinutes(x[0])>min);if(current){box.classList.add('live');box.textContent=`Сейчас: ${current[2]} · ещё ${toMinutes(current[1])-min} мин`}else if(next){const diff=toMinutes(next[0])-min;if(diff<=15)box.classList.add('soon');box.textContent=`Далее: ${next[2]} в ${next[0]} · через ${diff} мин`}else box.textContent='На сегодня занятия закончились'}
const dialog=$('#mapDialog'),frame=$('#mapFrame');
function mapUrl(room=''){return `aitumap/index.html?v=5-light${room?'&room='+encodeURIComponent(room):''}`}
function openMap(room='',subject=''){frame.src=mapUrl(room);$('#openMapTab').href=mapUrl(room);$('#mapTitle').textContent=room||'AITU Campus Map';$('#mapContext').textContent=subject?subject.toUpperCase():'КАРТА КАМПУСА';dialog.showModal();document.body.style.overflow='hidden'}
function closeMap(){dialog.close();document.body.style.overflow=''}
$('#openCampusMap').onclick=()=>openMap();$('#closeMap').onclick=closeMap;dialog.addEventListener('click',e=>{if(e.target===dialog)closeMap()});dialog.addEventListener('cancel',e=>{e.preventDefault();closeMap()});$('#expandMap').onclick=()=>{dialog.classList.toggle('expanded');$('#expandMap').textContent=dialog.classList.contains('expanded')?'↙':'⛶'};
const notify=$('#notifyButton');function setNotify(){const on='Notification'in window&&Notification.permission==='granted';notify.classList.toggle('on',on);notify.querySelector('.action-label').textContent=on?'Включены':'Уведомления'}notify.onclick=async()=>{if(!('Notification'in window))return;if(Notification.permission==='default')await Notification.requestPermission();setNotify()};
document.addEventListener('keydown',e=>{if(dialog.open)return;if(e.key==='ArrowLeft'){activeDay=activeDay<=1?6:activeDay-1;render()}if(e.key==='ArrowRight'){activeDay=activeDay>=6?1:activeDay+1;render()}});setNotify();render();setInterval(render,30000);
const deepRoom=new URLSearchParams(location.hash.slice(1)).get('room');if(deepRoom)openMap(deepRoom,'Выбранный кабинет');
